language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="mirage-device"
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.06
   - DISTRO=alpine OCAML_VERSION=4.07
   - DISTRO=alpine OCAML_VERSION=4.08
   - DISTRO=alpine OCAML_VERSION=4.09
